baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.TrackTEK.ai" # the base hostname & protocol for your site, e.g. http://example.com
permalink: "/:title"

# Build settings
theme: minima

repository: DevGlitch/TrackTEK.ai